title: "Total Assist - Servicios IT"
description: "Ofrecemos soluciones IT personalizadas para empresas"
theme: jekyll-theme-cayman # O el tema que prefieras
url: "https://dannyvergel.github.io/totalassist.github.io" 
baseurl: "/totalassist.github.io" 
